### ISSUE TITLE
Relacionar la transferencia para ACEPTAR 

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/bill_transferencias#2]
Relacionar para que acepte la transferencia el USUARIO con su BODEGA y no cualquier usuario ya que esto es un falta de seguridad en productos.

**Comment by jaimejhonle** [comment]
Se elimino la opcion de elegir bodega al realizar una transferencia, ya q a un empleado deberia corresponderle implicitamente una bodega con esta correccion se ha dado solucion a este inconveniente queda aun pendiente en el modulo de transferencias Modificar Transferencia
