### ISSUE TITLE
Colocar el nombre Transferemcias+Numero para Kardex bodegas 

### ISSUE THREAD

**Issue by edymac** [MASTERPC-CIA/bill_transferencias#3]
Cuando se hace seguimiento en kardes / kardex bodega se debe mostrar que fue una transferencia + el numero de la transferencia con el objetivo de dar seguimiento al movimiento del inventario, actualmente esta mal porque se muestra como AJUSTE DE SALIDA Y ENTRADA

**Comment by jaimejhonle** [comment]
Se ha hecho la correcion al realizar una transferencia esta se registre con el tipo de transaccion correspondiente
